[package]
name = "nyxdb"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
env_logger = { version = "0.11.8", features = ["color"] }
log = "0.4.28"
polars = { version = "0.51.0", features = ["lazy", "parquet"] }
thiserror = "2.0.17"
